Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': []
    '%w': []

Style/RedundantFreeze:
  Enabled: true

Style/MutableConstant:
  Enabled: false
